config/routes.rb
Rails.application.routes.draw do
  get 'inicio/index'
  devise_for :users
  resources :trabajos
  resources :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "inicio#index"

=begin
  unauthenticated do
    root :to => 'inicio#index'
  end

  authenticated do
    root :to => 'trabajos#index'
  end
=end
end

app/models/trabajo.rb
class Trabajo < ApplicationRecord
    has_and_belongs_to_many :usuarios
end

app/controllers/trabajos_controller.rb
class TrabajosController < ApplicationController
  before_action :set_trabajo, only: %i[ show edit update destroy ]

  # GET /trabajos or /trabajos.json
  def index
    @trabajos = Trabajo.all
  end

  # GET /trabajos/1 or /trabajos/1.json
  def show
  end

  # GET /trabajos/new
  def new
    @trabajo = Trabajo.new
  end

  # GET /trabajos/1/edit
  def edit
  end

  # POST /trabajos or /trabajos.json
  def create
    @trabajo = Trabajo.new(trabajo_params)

    respond_to do |format|
      if @trabajo.save
        format.html { redirect_to trabajo_url(@trabajo), notice: "se creo exitosamente." }
        format.json { render :show, status: :created, location: @trabajo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trabajos/1 or /trabajos/1.json
  def update
    respond_to do |format|
      if @trabajo.update(trabajo_params)
        format.html { redirect_to trabajo_url(@trabajo), notice: "La oferta de trabajo fue actualizada." }
        format.json { render :show, status: :ok, location: @trabajo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @trabajo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trabajos/1 or /trabajos/1.json
  def destroy
    @trabajo.destroy

    respond_to do |format|
      format.html { redirect_to trabajos_url, notice: "oferta de trabajo fue exitosamente eliminado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trabajo
      @trabajo =Trabajo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def trabajo_params
      params.require(:trabajo).permit(:puesto, :descripción)
    end
end

app/helpers/trabajos_helper.rb
module TrabajosHelper
end

app/views/trabajos/_form.html.erb
<%= form_with(model: trabajo) do |form| %>
  <% if trabajo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(trabajo.errors.count, "error") %> prohibited this trabajo from being saved:</h2>

      <ul>
        <% trabajo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :puesto, style: "display: block" %>
    <%= form.text_field :puesto %>
  </div>

  <div>
    <%= form.label :descripción, style: "display: block" %>
    <%= form.text_field :descripción %>
  </div>

  <div>
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/trabajos/_trabajo.html.erb
<div id="<%= dom_id trabajo %>">
  <p>
    <strong>Puesto:</strong>
    <%= trabajo.puesto %>
  </p>

  <p>
    <strong>Descripción:</strong>
    <%= trabajo.descripción %>
  </p>

</div>

app/views/trabajos/edit.html.erb
<h1>Editing trabajo</h1>

<%= render "form", trabajo: @trabajo %>

<br>

<div>
  <%= link_to "mostrar esta oferta", @trabajo %> |
  <%= link_to "regresar a trabajos", trabajos_path %>
</div>

app/views/trabajos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Trabajos</h1>

<div id="trabajos">
  <% @trabajos.each do |trabajo| %>
    <%= render trabajo %>
    <p>
      <%= link_to "Mostar", trabajo %>
    </p>
  <% end %>
</div>

<%= link_to "crear nueva oferta de trabajo", new_trabajo_path, class:"btn btn-success btn.btn-medium btn.btn-rounded" %>

app/views/trabajos/new.html.erb
<h1>Nueva oferta de trabajo</h1>

<%= render "form", trabajo: @trabajo %>

<br>

<div>
  <%= link_to "Regresar a ofertas laborales", trabajos_path %>
</div>

app/views/trabajos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @trabajo %>

<div>
  <%= link_to "Edit this trabajo", edit_trabajo_path(@trabajo) %> |
  <%= link_to "Back to trabajos", trabajos_path %>

  <%= button_to "eliminar esta oferta", @trabajo, method: :delete %>
</div>