config/routes.rb
Rails.application.routes.draw do
  get 'inicio/index'
  devise_for :users
  resources :trabajos
  resources :usuarios
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "inicio#index"

=begin
  unauthenticated do
    root :to => 'inicio#index'
  end

  authenticated do
    root :to => 'trabajos#index'
  end
=end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
    has_and_belongs_to_many :trabajos
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
    @postulación = Trabajo.id
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
    @trabajos = Trabajo.all
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to usuario_url(@usuario), notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy

    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :edad, :direccion, :telefono)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(usuario.errors.count, "error" ) %> prohibited this usuario from being saved:
      </h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li>
            <%= error.full_message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div>
        <%= form.label :Nombre, style: "display: block" %>
          <%= form.text_field :nombre %>
      </div>

      <div>
        <%= form.label :edad, style: "display: block" %>
          <%= form.text_field :edad %>
      </div>

      <div>
        <%= form.label :Direccion, style: "display: block" %>
          <%= form.text_field :direccion %>
      </div>

      <div>
        <%= form.label :Telefono, style: "display: block" %>
          <%= form.text_field :telefono %>
      </div>

      <div>
        <br>
        <label for="usuario_trabajo_id"> Elige tu postulación: </label>
        <select name="usuario[trabajo_id]" id="usuario_trabajo_id">
          <% @trabajos.each do |trabajo| %>
            <option value="<%= trabajo.id %>">
              <%= trabajo.id %> - <%= trabajo.puesto%>
            </option>
            <%end%>
        </select>
      </div>

      <div>
        <br>
        <%= form.submit class:"btn btn-primary " %>
  </div>
<% end %>

app/views/usuarios/_usuario.html.erb
<div id="<%= dom_id usuario %>">
  <p>
    <strong>Nombre:</strong>
    <%= usuario.nombre %>
  </p>

  <p>
    <strong>Edad:</strong>
    <%= usuario.edad %>
  </p>

  <p>
    <strong>Direccion:</strong>
    <%= usuario.direccion %>
  </p>

  <p>
    <strong>Telefono:</strong>
    <%= usuario.telefono %>
  </p>

</div>

app/views/usuarios/edit.html.erb
<h1>Editar Usuario </h1>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Mostrar Usuario", @usuario %> |
  <%= link_to "Regresar", usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Postulante</h1>

<div id="usuarios">
  <% @usuarios.each do |usuario| %>
    <%= render usuario %>
    <p>
      <%= link_to "Mostrar Postulante", usuario %>
    </p>
  <% end %>
</div>

<%= link_to "Nuevo usuario", new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Crear nuevo Usuario</h1>

<h2>Ingresa tus datos para postular </h2>

<%= render "form", usuario: @usuario %>

<br>

<div>
  <%= link_to "Regrasar", usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @usuario %>

<div>
  <%= link_to "Editar", edit_usuario_path(@usuario) %> |
  <%= link_to "Regresar", usuarios_path %>

  <%= button_to "Eliminar", @usuario, method: :delete %>
</div>